name: customer
description: Tribe customer app.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  datetime_picker_formfield: any
  pin_code_text_field: any
  shared_preferences: any
  url_launcher: any
  image_picker: any
  google_sign_in: any
  cached_network_image: any
  scoped_model: any
  firebase_messaging: any
  firebase_core: any
  flutter_webview_plugin: any
  connectivity: any
  device_info: any
  firebase_analytics: any
  google_maps_flutter: any
  share: any
  location: any
  package_info: any
  flutter_svg: any
  geolocator: any
  flutter_swiper: any
  flutter_spinkit: any
  qr_flutter: any
  shimmer: any
  pull_to_refresh: any
  firebase_dynamic_links: any
  graphql_flutter: any
  flutter_local_notifications: any
  json_annotation: any
  contacts_service: any
  contact_picker: any
  common:
    path: ../common
  aeyrium_sensor: any
  smooth_star_rating: any
  carousel_slider: any
  rxdart: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: any

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  
  fonts:
  - family: Product Sans
    fonts:
    - asset: fonts/productsansregular.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages